ARG BASEIMAGE=ubuntu:16.04
FROM $BASEIMAGE

RUN apt-get update && apt-get install -y python-pip python3-pip

# TODO do i need nose ?
RUN pip install pytest nose

RUN pip3 install pytest nose

ADD out/io/wheelhouse/* /tmp/

ARG WHL2FILE
ARG WHL3FILE

RUN pip install /tmp/$WHL2FILE

RUN pip3 install /tmp/$WHL3FILE

#Less error when running in build part so let's run it at docker run...
#RUN pip install /tmp/$WHL2FILE && python -c "import numpy; numpy.test()"
#RUN pip3 install /tmp/$WHL3FILE && python3 -c "import numpy; numpy.test()"